version: '3.2'
services:
  amqp:
    image: rabbitmq:4.0-management
  unittest:
    command: nose2 -vv
    build:
      context: .
      dockerfile: tests/Dockerfile
    depends_on:
      - amqp
    environment:
      AMQP_HOST: "amqp"
  stress_tests:
    build:
      context: .
      dockerfile: tests/Dockerfile
    command: python -m stress_tests
    depends_on:
      - amqp
    environment:
      AMQP_HOST: "amqp"
