version: '3.2'
services:
  amqp:
    image: rabbitmq:3-management
  unittest:
    build:
      context: .
      dockerfile: tests/Dockerfile
    depends_on:
      - amqp
    environment:
      AMQP_HOST: "amqp"
  stress_tests:
    build:
      context: .
      dockerfile: tests/Dockerfile
    command: python -m stress_tests
    depends_on:
      - amqp
    environment:
      AMQP_HOST: "amqp"
